### ISSUE TITLE
[Bug]: Can't build android app

### ISSUE THREAD

**Issue by karlovm** [Jigsaw-Code/outline-apps#2189]
### Application

Outline Client

### Describe the bug

Using official docs I've setup an environment and try to build.

Requirements output (I don't think android target impact this bug):

```
Requirements check results for android:
Java JDK: installed 11.0.0
Android SDK: installed true
Android target: not installed
Command failed with exit code 1: avdmanager list target
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more
Gradle: installed C:\Gradle\bin\gradle.BAT 
```

### Steps to reproduce

1. Clone git
2. Switch to node 18
3. Install go 1.21
4. Install android requireements
5. Run npm run action client/src/cordova/build android

### What did you expect to happen?

Build apk

### What actually happened?

Error building

### Outline Version

latest from github

### What operation system are you using?

Windows

### Operating System Version

dev 27686

### Screenshots and Videos

```

       / __ \| |  | |__   __| |    |_   _| \ | |  ____|
      | |  | | |  | |  | |  | |      | | |  \| | |__
      | |  | | |  | |  | |  | |      | | | . ` |  __|
      | |__| | |__| |  | |  | |____ _| |_| |\  | |____
       \____/ \____/   |_|  |______|_____|_| \_|______|

  =========================================================
               © The Outline Authors, 2023
  =========================================================

▶ action(client/src/cordova/build):
  Running [node '--trace-uncaught' 'D:\outline\outline-apps\client\src\cordova\build.action.mjs' 'android']...
  ▶ action(client/src/www/build):
    Running [node '--trace-uncaught' 'D:\outline\outline-apps\client\src\www\build.action.mjs' 'android']...
    (node:6856) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
    BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    (Use `node --trace-deprecation ...` to show where the warning was created)
  ▶ action(client/src/www/build): 🎉 Success! (18297ms)
  ▶ action(client/go/build):
    Running [node '--trace-uncaught' 'D:\outline\outline-apps\client\go\build.action.mjs' 'android']...
    Running [go 'run' 'github.com/go-task/task/v3/cmd/task' '-v' 'client:tun2socks:android']...
    task: [D:\outline\outline-apps] Not found - Using alternative (Taskfile.yml)
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1

    ERROR(spawn_stream): go run github.com/go-task/task/v3/cmd/task -v client:tun2socks:android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1

    node:internal/process/esm_loader:40
          internalBinding('errors').triggerUncaughtException(
                                    ^
    task: "client:tun2socks:android" startedtask: "client:tun2socks:gomobile" startedtask: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin""mkdir": executable file not found in $PATHexit status 127exit status 1
    Thrown at:
        at loadESM (node:internal/process/esm_loader:40:33)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)


    Node.js v18.20.4
    ERROR(spawn_stream): node --trace-uncaught D:\outline\outline-apps\client\go\build.action.mjs android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1
    ERROR(spawn_stream): go run github.com/go-task/task/v3/cmd/task -v client:tun2socks:android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1

    node:internal/process/esm_loader:40
          internalBinding('errors').triggerUncaughtException(
                                    ^
    task: "client:tun2socks:android" startedtask: "client:tun2socks:gomobile" startedtask: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin""mkdir": executable file not found in $PATHexit status 127exit status 1
    Thrown at:
        at loadESM (node:internal/process/esm_loader:40:33)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)


    Node.js v18.20.4
  ▶ action(client/go/build): ❌ Failed.
  ERROR(spawn_stream): node --trace-uncaught D:\outline\outline-apps\client\src\cordova\build.action.mjs android failed with exit code 1.}
  Printing stderr:
    (node:6856) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
    BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1
    ERROR(spawn_stream): go run github.com/go-task/task/v3/cmd/task -v client:tun2socks:android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1

    node:internal/process/esm_loader:40
          internalBinding('errors').triggerUncaughtException(
                                    ^
    task: "client:tun2socks:android" startedtask: "client:tun2socks:gomobile" startedtask: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin""mkdir": executable file not found in $PATHexit status 127exit status 1
    Thrown at:
        at loadESM (node:internal/process/esm_loader:40:33)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)


    Node.js v18.20.4
    ERROR(spawn_stream): node --trace-uncaught D:\outline\outline-apps\client\go\build.action.mjs android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1
    ERROR(spawn_stream): go run github.com/go-task/task/v3/cmd/task -v client:tun2socks:android failed with exit code 1.}
    Printing stderr:
    task: "client:tun2socks:android" started
    task: "client:tun2socks:gomobile" started
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1

    node:internal/process/esm_loader:40
          internalBinding('errors').triggerUncaughtException(
                                    ^
    task: "client:tun2socks:android" startedtask: "client:tun2socks:gomobile" startedtask: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin""mkdir": executable file not found in $PATHexit status 127exit status 1
    Thrown at:
        at loadESM (node:internal/process/esm_loader:40:33)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)


    Node.js v18.20.4
  ▶ action(client/go/build): ❌ Failed.
▶ action(client/src/cordova/build): ❌ Failed.
```

**Comment by sbruens** [comment]
```sh
    task: [client:tun2socks:gomobile] mkdir -p "D:\outline\outline-apps\client\output\build\bin"
    "mkdir": executable file not found in $PATH
    exit status 127
    exit status 1
```
It seems you don't have `mkdir` installed. Can you confirm you are using the default PowerShell instead of a customized shell?

**Comment by sbruens** [comment]
Hi there,

We're closing this issue due to inactivity. We haven't heard back from you in a while, and aim to keep our issue tracker organized.

If you're still experiencing this problem or have any additional information to share, please feel free to reopen this issue or create a new one.

Thank you for your understanding!
