### ISSUE TITLE
[Bug]: java.lang.module.FindException: Module java.se.ee not found

### ISSUE THREAD

**Issue by sijjeel** [Jigsaw-Code/outline-apps#2237]
### Application

Outline Client

### Describe the bug

I have used java 11 as mentioned in the requirements and which i tried to install the build-tools using following command.

$HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"

it says you should use java 17 or above.

then i switched my java version to 17 and updated my Java home path in ~/.zshrc file and ran the same command. It's giving me following error.

$HOME/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0"
Error occurred during initialization of boot layer
java.lang.module.FindException: Module [java.se.ee](http://java.se.ee/) not found

### Steps to reproduce

When i run cordova requirements It gives following error.

npx cordova requirements android

Requirements check results for android:
Java JDK: installed 17.0.12
Android SDK: installed true
Android target: not installed 
Command failed with exit code 1: avdmanager list target
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found
Gradle: installed /opt/homebrew/Cellar/gradle/8.10.2/bin/gradle
Some of requirements check failed

Any help will be greatly appreciated.

### Outline Version

Latest

### What operation system are you using?

Android

### Operating System Version

Sequoia 15.0

**Comment by sbruens** [comment]
You need to switch to Java 11 when building Outline, even if you have installed Java 17. Did you follow https://github.com/Jigsaw-Code/outline-apps/blob/master/client/src/cordova/android/README.md?

**Comment by sijjeel** [comment]
> You need to switch to Java 11 when building Outline, even if you have installed Java 17. Did you follow https://github.com/Jigsaw-Code/outline-apps/blob/master/client/src/cordova/android/README.md?

I have used java 11 and it gives me following error.

`npx cordova requirements android 

Requirements check results for android:
Java JDK: installed 11.0.24
Android SDK: installed true
Android target: not installed 
Command failed with exit code 1: avdmanager list target
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 5 more
Gradle: installed /opt/homebrew/Cellar/gradle/8.10.2/bin/gradle
Some of requirements check failed`

**Comment by sbruens** [comment]
Hi there,

We're closing this issue due to inactivity. We haven't heard back from you in a while, and aim to keep our issue tracker organized.

If you're still experiencing this problem or have any additional information to share, please feel free to reopen this issue or create a new one.

Thank you for your understanding!
