### ISSUE TITLE
[Bug]: Don`t have permissions for start routing deamon tun2socks on Debian

### ISSUE THREAD

**Issue by kirnil** [Jigsaw-Code/outline-apps#2294]
### Application

Outline Client

### Describe the bug

Couldn`t start routing daemon tun2socks, don`t have permissions.

### Steps to reproduce

Debian 12, KDE 5.27 Wayland

1. Download APP from [Ouline get started](https://getoutline.org/get-started/)
2. `chmod u+x  ~/Outline-Client.AppImage`
3. Start from `~/Outline-Client.AppImage`

### What did you expect to happen?

I expected a window to appear for entering the Administrator password. After a warning window indicating the need for administrator rights.

### What actually happened?

Apart from a window warning about a possible request for Administrator rights, nothing started.

### Outline Version

1.14.0 (480310)

### What operation system are you using?

Linux

### Operating System Version

Debian 12

### Screenshots and Videos

``` bash
$ ./Outline-Client.AppImage
Outline is  #starting
loading web app from file:///tmp/.mount_OutlinRtt6ud/resources/app.asar/client/www/index_electron.html?appName=Outline
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open '/home/debian/.config/Outline/connection_store'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/debian/.config/Outline/connection_store'
}
Checking for update
Update for version 1.14.0 is not available (latest version: 1.14.0, downgrade is disallowed).
[16736:1124/135108.009679:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[16736:1124/135125.717753:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16736:1124/135136.285176:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
connecting to mpsrv Outline (7XXXXX95-XXXX-XXXX-XXXX-dbXXXXXX1d17)...
[tun2socks] - checking connectivity ...
[tun2socks - EXIT]: Exited with code 0
UDP support: true
starting routing daemon
[tun2socks] - starting to route network traffic ...
Routing daemon socket setup failed Error: connect ENOENT /var/run/outline_controller
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/outline_controller'
}
could not connect: Error: {"code":"ERR_ROUTING_SERVICE_NOT_RUNNING","message":"routing daemon is not running","cause":{"code":"ERR_INTERNAL_ERROR","message":"Error: connect ENOENT /var/run/outline_controller"}}
    at Socket.r (/tmp/.mount_OutlinRtt6ud/resources/app.asar/output/client/electron/index.js:2:678675)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Error occurred in handler for 'outline-ipc-start-proxying': Error: {"code":"ERR_ROUTING_SERVICE_NOT_RUNNING","message":"routing daemon is not running","cause":{"code":"ERR_INTERNAL_ERROR","message":"Error: connect ENOENT /var/run/outline_controller"}}
    at Socket.r (/tmp/.mount_OutlinRtt6ud/resources/app.asar/output/client/electron/index.js:2:678675)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[tun2socks - EXIT]: Exited with code 1
[tun2socks] - terminated due to: a [Error]: {"code":"ERR_SYSTEM_VPN_SETUP_FAILURE","message":"failed to open TUN device","cause":{"code":"ERR_INTERNAL_ERROR","message":"ioctl: operation not permitted"}}

    at t.ChildProcessHelper.b (/tmp/.mount_OutlinRtt6ud/resources/app.asar/output/client/electron/index.js:2:674688)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  exitCode: 1
}
could not stop tun2socks: {"code":"ERR_SYSTEM_VPN_SETUP_FAILURE","message":"failed to open TUN device","cause":{"code":"ERR_INTERNAL_ERROR","message":"ioctl: operation not permitted"}}

disconnected from 7XXXXXX5-XXXX-XXXX-XXXX-dbXXXXXX1d17
installing outline routing service...
copying service installation files to /tmp/kCMgp2
all service installation files copied to /tmp/kCMgp2 successfully
trying to run command as root:  trap "/usr/bin/chattr -R -i /tmp/kCMgp2" EXIT; /usr/bin/chattr -R +i /tmp/kCMgp2 && /usr/bin/echo "e06XXXXXXXXXXXXXXXXXXXe2e7de0de1e46386eed713d7141f15d9e4XX53c1cd  /tmp/kCMgp2/install_linux_service.sh" | /usr/bin/shasum -a 256 -c && /usr/bin/echo "0a2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXebb4f4057e06620b7fdC4a  /tmp/kCMgp2/OutlineProxyController" | /usr/bin/shasum -a 256 -c && /usr/bin/echo "8bfaXXXXXXXXXXXXXXXXXXXXXXXXXXXXbf8c2d365a2a7f3b6c0X32c2aXc915a2  /tmp/kCMgp2/outline_proxy_controller.service" | /usr/bin/shasum -a 256 -c && "/tmp/kCMgp2/install_linux_service.sh" "debian"
undefined
undefined
command is running as root but failed:  Error: Unable to find pkexec or kdesudo.
    at e (/tmp/.mount_OutlinRtt6ud/resources/app.asar/output/client/electron/index.js:2:642401)
    at /tmp/.mount_OutlinRtt6ud/resources/app.asar/output/client/electron/index.js:2:642554
    at FSReqCallback.oncomplete (node:fs:198:21)
^C^C
```
![Screenshot_20241124_150033](https://github.com/user-attachments/assets/60bca4b1-249b-4a48-878a-ab9f9c39d777)

**Comment by kirnil** [comment]
To fix the problem you need to install pkexec or kdesudo.
I choose `apt install pkexec` and i got a window to enter the root password

![Screenshot_20241124_151910](https://github.com/user-attachments/assets/dc446a08-f9b7-4b34-87a2-2f9682956599)
