### ISSUE TITLE
Cannot find module '../dialog'

### ISSUE THREAD

**Issue by yuexiangqianlong** [Jigsaw-Code/outline-apps#679]
Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/tmp/.mount_Outlinpcpy7B/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/tmp/.mount_Outlinpcpy7B/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/tmp/.mount_Outlinpcpy7B/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)
===================================================================

Operating environment Ubuntu 18.04

**Comment by JonathanDCohen** [comment]
Can you try running `yarn run clean && yarn` first?  The retry running the client and see what happens.

**Comment by sbruens** [comment]
Hi there,

We're closing this issue due to inactivity. We haven't heard back from you in a while, and aim to keep our issue tracker organized.

If you're still experiencing this problem or have any additional information to share, please feel free to reopen this issue or create a new one.

Thank you for your understanding!
