### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by PIshdadNetwork** [Jigsaw-Code/outline-apps#725]
Hi
I cant build from source I get this error ( for web app )

```
yarn gulp build --platform=browser
yarn run v1.13.0-20181121.1436
$ /mnt/c/ocm/node_modules/.bin/gulp build --platform=browser
[01:12:27] Using gulpfile /mnt/c/ocm/gulpfile.js
[01:12:27] Starting 'build'...
[01:12:27] Starting 'buildWebApp'...
$ bash ./scripts/do_action.sh src/www/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/mnt/c/ocm
+ ROOT_DIR=/mnt/c/ocm
[Running src/www/build]
+ export BUILD_DIR=/mnt/c/ocm/build
+ BUILD_DIR=/mnt/c/ocm/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ /mnt/c/ocm/src/www/build_action.sh
+ tsc -p src/www
src/www/app/main.ts(79,68): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'EnvironmentVariables'.
src/www/app/main.ts(80,17): error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'EnvironmentVariables'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[01:12:31] 'buildWebApp' errored after 4.78 s
[01:12:31] Error: exited with error code: 1
    at ChildProcess.onexit (/mnt/c/ocm/node_modules/end-of-stream/index.js:40:36)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[01:12:31] 'build' errored after 4.78 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Environment**
 - OS: Ubuntu 18.04 LTS
 - Yarn 1.13.0-20181121.1436
 - Node.js v8.10.0

**Additional context**

**Comment by llango** [comment]
Same problem, Who can figure out the problem?

**Comment by JonathanDCohen** [comment]
You may be using an ald version of electron or node.  Make sure you're using up-to-date source and try to `yarn run clean && yarn` to refresh your dependencies

**Comment by Abhishekk24** [comment]
This indicates that there is an issue with the types in your TypeScript code. TypeScript is complaining that something of type 'unknown' is being assigned to a variable or parameter that should be of type 'EnvironmentVariables'

**Comment by sbruens** [comment]
We're closing this issue due to inactivity. If you're still experiencing problems or have any further questions, please feel free to reopen this issue or create a new one.
